### PR TITLE
Fix specs & align testing rig

### PR DESCRIPTION
**Pull request by Phil-Friderici**
This will remove automatic testing of Rubocop. *.rb files need fixes before it can get turned on again.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
Man, this was a beach.
Hope it's ok to continue without Rubocop for the moment.

**Comment by propyless** [comment]
lmao, shit just got serious when you are the one to say that something Ruby related is a beach :P......

**Comment by Phil-Friderici** [comment]
hehehe, was a collection of different details. Everytime I fixed one, the next one popped up...
Are you ok to continue without Rubocop ?

**Comment by propyless** [comment]
For me its fine :P

**Comment by Phil-Friderici** [comment]
Hope life is good to you :) Have a nice weekend soon !

**Comment by propyless** [comment]
I sent you an email a week or so ago! but you didn't respond :'(

Yupp yupp, have a nice weekend :)

**Comment by Phil-Friderici** [comment]
Uh! Private or Company mail ?

**Comment by propyless** [comment]
Private

**Pull request merged**
